git mv Stratis.Benchmark                                       Blockcore.Benchmark
git mv Stratis.Bitcoin                                         Blockcore
git mv Stratis.Bitcoin.Api.Tests                               Blockcore.Features.Api.Tests
git mv Stratis.Bitcoin.Cli                                     Blockcore.Cli
git mv Stratis.Bitcoin.Features.Api                            Blockcore.Features.Api
git mv Stratis.Bitcoin.Features.BlockStore                     Blockcore.Features.BlockStore
git mv Stratis.Bitcoin.Features.BlockStore.Tests               Blockcore.Features.BlockStore.Tests
git mv Stratis.Bitcoin.Features.ColdStaking                    Blockcore.Features.ColdStaking
git mv Stratis.Bitcoin.Features.ColdStaking.Tests              Blockcore.Features.ColdStaking.Tests
git mv Stratis.Bitcoin.Features.Consensus                      Blockcore.Features.Consensus
git mv Stratis.Bitcoin.Features.Consensus.Tests                Blockcore.Features.Consensus.Tests
git mv Stratis.Bitcoin.Features.Dns                            Blockcore.Features.Dns
git mv Stratis.Bitcoin.Features.Dns.Tests                      Blockcore.Features.Dns.Tests
git mv Stratis.Bitcoin.Features.LightWallet                    Blockcore.Features.LightWallet
git mv Stratis.Bitcoin.Features.MemoryPool                     Blockcore.Features.MemoryPool
git mv Stratis.Bitcoin.Features.MemoryPool.Tests               Blockcore.Features.MemoryPool.Tests
git mv Stratis.Bitcoin.Features.Miner                          Blockcore.Features.Miner
git mv Stratis.Bitcoin.Features.Miner.Tests                    Blockcore.Features.Miner.Tests
git mv Stratis.Bitcoin.Features.PoA                            Blockcore.Features.PoA
git mv Stratis.Bitcoin.Features.PoA.IntegrationTests           Blockcore.Features.PoA.IntegrationTests
git mv Stratis.Bitcoin.Features.PoA.IntegrationTests.Common    Blockcore.Features.PoA.IntegrationTests.Common
git mv Stratis.Bitcoin.Features.PoA.Tests                      Blockcore.Features.PoA.Tests
git mv Stratis.Bitcoin.Features.RPC                            Blockcore.Features.RPC
git mv Stratis.Bitcoin.Features.RPC.Tests                      Blockcore.Features.RPC.Tests
git mv Stratis.Bitcoin.Features.SignalR                        Blockcore.Features.SignalR
git mv Stratis.Bitcoin.Features.Wallet                         Blockcore.Features.Wallet
git mv Stratis.Bitcoin.Features.Wallet.Tests                   Blockcore.Features.Wallet.Tests
git mv Stratis.Bitcoin.Features.WatchOnlyWallet                Blockcore.Features.WatchOnlyWallet
git mv Stratis.Bitcoin.Features.WatchOnlyWallet.Tests          Blockcore.Features.WatchOnlyWallet.Tests
git mv Stratis.Bitcoin.IntegrationTests                        Blockcore.IntegrationTests
git mv Stratis.Bitcoin.IntegrationTests.Common                 Blockcore.IntegrationTests.Common
git mv Stratis.Bitcoin.Networks                                Blockcore.Networks
git mv Stratis.Bitcoin.Tests                                   Blockcore.Tests
git mv Stratis.Bitcoin.Tests.Common                            Blockcore.Tests.Common
git mv Stratis.Bitcoin.Tests.Wallet.Common                     Blockcore.Tests.Wallet.Common
git mv Stratis.BitcoinD                                        Bitcoin
git mv Stratis.Features.Diagnostic                             Blockcore.Features.Diagnostic
git mv Stratis.StratisD                                        Stratis
git mv Stratis.StratisDnsD                                     StratisDns


