git mv Bitcoin\Stratis.BitcoinD.csproj                                                                                  Bitcoin\BitcoinD.csproj
git mv Blockcore\Stratis.Bitcoin.csproj                                                                                 Blockcore\Blockcore.csproj
git mv Blockcore.Benchmark\Stratis.Benchmark.csproj                                                                     Blockcore.Benchmark\Blockcore.Benchmark.csproj
git mv Blockcore.Cli\Stratis.Bitcoin.Cli.csproj                                                                         Blockcore.Cli\Blockcore.Cli.csproj
git mv Blockcore.Features.Api\Stratis.Bitcoin.Features.Api.csproj                                                       Blockcore.Features.Api\Blockcore.Features.Api.csproj
git mv Blockcore.Features.Api.Tests\Stratis.Bitcoin.Api.Tests.csproj                                                    Blockcore.Features.Api.Tests\Blockcore.Api.Tests.csproj
git mv Blockcore.Features.BlockStore\Stratis.Bitcoin.Features.BlockStore.csproj                                         Blockcore.Features.BlockStore\Blockcore.Features.BlockStore.csproj
git mv Blockcore.Features.BlockStore.Tests\Stratis.Bitcoin.Features.BlockStore.Tests.csproj                             Blockcore.Features.BlockStore.Tests\Blockcore.Features.BlockStore.Tests.csproj
git mv Blockcore.Features.ColdStaking\Stratis.Bitcoin.Features.ColdStaking.csproj                                       Blockcore.Features.ColdStaking\Blockcore.Features.ColdStaking.csproj
git mv Blockcore.Features.ColdStaking.Tests\Stratis.Bitcoin.Features.ColdStaking.Tests.csproj                           Blockcore.Features.ColdStaking.Tests\Blockcore.Features.ColdStaking.Tests.csproj
git mv Blockcore.Features.Consensus\Stratis.Bitcoin.Features.Consensus.csproj                                           Blockcore.Features.Consensus\Blockcore.Features.Consensus.csproj
git mv Blockcore.Features.Consensus.Tests\Stratis.Bitcoin.Features.Consensus.Tests.csproj                               Blockcore.Features.Consensus.Tests\Blockcore.Features.Consensus.Tests.csproj
git mv Blockcore.Features.Diagnostic\Stratis.Features.Diagnostic.csproj                                                 Blockcore.Features.Diagnostic\Blockcore.Features.Diagnostic.csproj
git mv Blockcore.Features.Dns\Stratis.Bitcoin.Features.Dns.csproj                                                       Blockcore.Features.Dns\Blockcore.Features.Dns.csproj
git mv Blockcore.Features.Dns.Tests\Stratis.Bitcoin.Features.Dns.Tests.csproj                                           Blockcore.Features.Dns.Tests\Blockcore.Features.Dns.Tests.csproj
git mv Blockcore.Features.LightWallet\Stratis.Bitcoin.Features.LightWallet.csproj                                       Blockcore.Features.LightWallet\Blockcore.Features.LightWallet.csproj
git mv Blockcore.Features.MemoryPool\Stratis.Bitcoin.Features.MemoryPool.csproj                                         Blockcore.Features.MemoryPool\Blockcore.Features.MemoryPool.csproj
git mv Blockcore.Features.MemoryPool.Tests\Stratis.Bitcoin.Features.MemoryPool.Tests.csproj                             Blockcore.Features.MemoryPool.Tests\Blockcore.Features.MemoryPool.Tests.csproj
git mv Blockcore.Features.Miner\Stratis.Bitcoin.Features.Miner.csproj                                                   Blockcore.Features.Miner\Blockcore.Features.Miner.csproj
git mv Blockcore.Features.Miner.Tests\Stratis.Bitcoin.Features.Miner.Tests.csproj                                       Blockcore.Features.Miner.Tests\Blockcore.Features.Miner.Tests.csproj
git mv Blockcore.Features.PoA\Stratis.Bitcoin.Features.PoA.csproj                                                       Blockcore.Features.PoA\Blockcore.Features.PoA.csproj
git mv Blockcore.Features.PoA.IntegrationTests\Stratis.Bitcoin.Features.PoA.IntegrationTests.csproj                     Blockcore.Features.PoA.IntegrationTests\Blockcore.Features.PoA.IntegrationTests.csproj
git mv Blockcore.Features.PoA.IntegrationTests.Common\Stratis.Bitcoin.Features.PoA.IntegrationTests.Common.csproj       Blockcore.Features.PoA.IntegrationTests.Common\Blockcore.Features.PoA.IntegrationTests.Common.csproj
git mv Blockcore.Features.PoA.Tests\Stratis.Bitcoin.Features.PoA.Tests.csproj                                           Blockcore.Features.PoA.Tests\Blockcore.Features.PoA.Tests.csproj
git mv Blockcore.Features.RPC\Stratis.Bitcoin.Features.RPC.csproj                                                       Blockcore.Features.RPC\Blockcore.Features.RPC.csproj
git mv Blockcore.Features.RPC.Tests\Stratis.Bitcoin.Features.RPC.Tests.csproj                                           Blockcore.Features.RPC.Tests\Blockcore.Features.RPC.Tests.csproj
git mv Blockcore.Features.SignalR\Stratis.Bitcoin.Features.SignalR.csproj                                               Blockcore.Features.SignalR\Blockcore.Features.SignalR.csproj
git mv Blockcore.Features.Wallet\Stratis.Bitcoin.Features.Wallet.csproj                                                 Blockcore.Features.Wallet\Blockcore.Features.Wallet.csproj
git mv Blockcore.Features.Wallet.Tests\Stratis.Bitcoin.Features.Wallet.Tests.csproj                                     Blockcore.Features.Wallet.Tests\Blockcore.Features.Wallet.Tests.csproj
git mv Blockcore.Features.WatchOnlyWallet\Stratis.Bitcoin.Features.WatchOnlyWallet.csproj                               Blockcore.Features.WatchOnlyWallet\Blockcore.Features.WatchOnlyWallet.csproj
git mv Blockcore.Features.WatchOnlyWallet.Tests\Stratis.Bitcoin.Features.WatchOnlyWallet.Tests.csproj                   Blockcore.Features.WatchOnlyWallet.Tests\Blockcore.Features.WatchOnlyWallet.Tests.csproj
git mv Blockcore.IntegrationTests\Stratis.Bitcoin.IntegrationTests.csproj                                               Blockcore.IntegrationTests\Blockcore.IntegrationTests.csproj
git mv Blockcore.IntegrationTests.Common\Stratis.Bitcoin.IntegrationTests.Common.csproj                                 Blockcore.IntegrationTests.Common\Blockcore.IntegrationTests.Common.csproj
git mv Blockcore.Networks\Stratis.Bitcoin.Networks.csproj                                                               Blockcore.Networks\Blockcore.Networks.csproj
git mv Blockcore.Tests\Stratis.Bitcoin.Tests.csproj                                                                     Blockcore.Tests\Blockcore.Tests.csproj
git mv Blockcore.Tests.Common\Stratis.Bitcoin.Tests.Common.csproj                                                       Blockcore.Tests.Common\Blockcore.Tests.Common.csproj
git mv Blockcore.Tests.Wallet.Common\Stratis.Bitcoin.Tests.Wallet.Common.csproj                                         Blockcore.Tests.Wallet.Common\Blockcore.Tests.Wallet.Common.csproj
git mv Stratis\Stratis.StratisD.csproj                                                                                  Stratis\StratisD.csproj
git mv StratisDns\Stratis.StratisDnsD.csproj                                                                            StratisDns\StratisDnsD.csproj