name: Publish Release Packages

on:
  release:
    types: [published]
  repository_dispatch:
    types: [publish-packages]
  workflow_dispatch:

jobs:

  publishPackages:

    runs-on: windows-latest
    
    env:
      SOLUTION_PATH: 'src/Blockcore.sln'
      BUILD_CONFIGURATION: 'Release'

    steps:

    - uses: actions/checkout@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Nuget Pack
      run: dotnet pack --configuration ${{env.BUILD_CONFIGURATION}} --output "${{github.workspace}}\package\" ${{env.SOLUTION_PATH}}

    - name: Nuget Push
      run: nuget push ${{github.workspace}}\package\*.nupkg -ApiKey ${{secrets.NUGET_KEY}} -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate -NoSymbols