name: Publish Release Packages

on:
  release:
    types: [published]
  repository_dispatch:
    types: [publish-packages]
  workflow_dispatch:

jobs:

  publishPackages:

    runs-on: windows-latest
    
    env:
      SOLUTION_PATH: 'src/Blockcore.sln'
      BUILD_CONFIGURATION: 'Release'

    steps:

    - uses: actions/checkout@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    # - name: Set GITHUB_OWNER
    #   run: echo "::set-env name=GITHUB_OWNER::$(echo ${{github.repository}} | cut -d "/" -f 1)"

    # - name: Override bash shell PATH (workaround issue - tinyurl.com/w3dbtou)
    #   run: echo "::add-path::C:\Program Files\Git\bin"
    
    # - name: Update Directory.Build.props for Push
    #   run: |
    #     find . -name 'Directory.Build.props' -print0 | while read -d $'\0' file
    #     do
    #       sed -i 's,</IsPackable>,</IsPackable>\n\t<RepositoryType>git</RepositoryType>\n\t<RepositoryUrl>git://github.com/${{github.repository}}</RepositoryUrl>,g' $file
    #     done
    #   shell: bash

    - name: Nuget Pack
      run: dotnet pack --configuration ${{env.BUILD_CONFIGURATION}} --output "${{github.workspace}}\package\" ${{env.SOLUTION_PATH}}

    - name: Nuget Push
      run: nuget push ${{github.workspace}}\package\*.nupkg -ApiKey ${{secrets.NUGET_KEY}} -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate -NoSymbols